### PR TITLE
docs: roadmap

### PR DESCRIPTION
**Pull request by j-zimnowoda**
I invited everyone from DEV team, so everyone has a chance express their opinion about our roadmap.
@srodenhuis please do not merge it until we have consensus here.

### CODE REVIEW

**Comment by srodenhuis** [comment]
Looks good! Maybe explain the difference between team and application dashboards.

**Review by dennisvankekem — APPROVED** [review]
LGTM

**Review by ElderMatt — APPROVED** [review]
Very Nice

**Review by ferruhcihan — APPROVED** [review]
LGTM

**Review by Ani1357 — APPROVED** [review]

**Review by merll — APPROVED** [review]

**Review by staticvoid255 — APPROVED** [review]

**Review by ElderMatt — APPROVED** [review]

**Pull request merged**
