### PR TITLE
fix: landing page, menu

### PR DESCRIPTION
**Pull request by Morriz**
I have brought back the landing page and simplified the main menu.

### CODE REVIEW

**Comment by dennisvankekem** [comment]
Because you added the header menu back you should consider removing this part in `custom.css`

```
.navbar-sidebar__back {
  display: none
}
```
Because right now the mobile drawer menu isn't able to navigate back to the other topics.

**Review by srodenhuis — APPROVED** [review]
LGTM (now)

**Comment by Morriz** [comment]
> Because you added the header menu back you should consider removing this part in custom.css
> 
> ```
> .navbar-sidebar__back {
>  display: none
> }
> ```

@srodenhuis did you implement Dennis' suggestion?

**Comment by srodenhuis** [comment]
Yep

**Pull request merged**
