### PR TITLE
Enhancement idea

### PR DESCRIPTION
**Pull request by svatwork**
I was actually missing from this website the answer to the question: "What is Kubernetes?"

Maybe we could also do it for other applications (e.g. no idea what any of these apps is useful for). I just wonder if most people even know what it is, I get this question asked frequently by friends (business or otherwise) and family. 

Inspiration: https://www.reddit.com/r/devops/comments/pl02p3/what_problems_have_you_actually_solved_with/.

### CODE REVIEW

**Comment by svatwork** [comment]
The href attribute is quite subtle and not interrupting the rest of the page, but if you hover over it it gives some nice interactivity.

**Review by Morriz — COMMENTED** [review]
seems helpful, but I wonder what it looks like...can you post a screenshot of the front page?

**Comment by svatwork** [comment]
Without hover (no change):

Screenshot 2021-09-14 at 08 43 25

With hover:

Screenshot 2021-09-14 at 08 43 38

**Review by Morriz — APPROVED** [review]
tnx

**Comment by svatwork** [comment]
I want to do it for other useful stuff on the website as well, what do you think? Should I create an (enhancement) issue?

**Comment by Morriz** [comment]
Sure. But if it is more than 10 minutes of work please park it in zenhub...

**Comment by svatwork** [comment]
Yes of course :)

**Pull request merged**
